import os
from datetime import datetime
from typing import List, Dict, Any

class ReportGenerator:
    def __init__(self):
        self.reports_dir = "reports"
        os.makedirs(self.reports_dir, exist_ok=True)
        
    def create_report(self, contract_name: str, chain: str, source_code: str, 
                     vulnerabilities: List[Dict], pocs: List[Dict], summary: str) -> Dict[str, str]:
        """
        Generate comprehensive markdown report
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{contract_name}_{timestamp}.md"
        filepath = os.path.join(self.reports_dir, filename)
        
        # Build markdown
        md = f"""# Security Audit Report: {contract_name}

**Chain**: {chain.upper()}  
**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Generated by**: Web3 Hunter (RAG-Enhanced AI Analysis)

---

## Executive Summary

{summary}

**Total Vulnerabilities Found**: {len(vulnerabilities)}
- **Critical**: {sum(1 for v in vulnerabilities if v['severity'] == 'Critical')}
- **High**: {sum(1 for v in vulnerabilities if v['severity'] == 'High')}
- **Medium**: {sum(1 for v in vulnerabilities if v['severity'] == 'Medium')}
- **Low**: {sum(1 for v in vulnerabilities if v['severity'] == 'Low')}

---

## Detailed Findings

"""
        
        for idx, vuln in enumerate(vulnerabilities, 1):
            severity_emoji = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}.get(vuln['severity'], "⚪")
            
            md += f"""### {idx}. {severity_emoji} {vuln['type']} ({vuln['severity']} Severity)

**Location**: Line {vuln['line']}  
**Confidence**: {vuln['confidence']*100:.0f}%

**Description**:  
{vuln['description']}

**Recommendation**:  
"""
            # Add specific recommendations
            if 'reentrancy' in vuln['type'].lower():
                md += """- Use the Checks-Effects-Interactions pattern
- Implement ReentrancyGuard from OpenZeppelin
- Update state before external calls
"""
            elif 'access' in vuln['type'].lower():
                md += """- Implement proper access control (onlyOwner, roles)
- Use OpenZeppelin AccessControl
- Audit all privileged functions
"""
            else:
                md += "- Review and apply security best practices\n"
            
            # Add PoC if available
            matching_poc = next((p for p in pocs if p['vulnerability'] == vuln['type']), None)
            if matching_poc:
                md += f"""
**Proof of Concept**:
```solidity
{matching_poc['code']}
```
PoC File: `{matching_poc['poc_file']}`
"""
            md += "\n---\n\n"
        
        # Add source code
        md += f"""## Contract Source Code

```solidity
{source_code}
```

---

## Methodology

This audit was performed using:
- **RAG-Enhanced AI Analysis**: Leveraging a database of 143+ known vulnerabilities
- **Local LLM**: Qwen 2.5 Coder (7B parameters)
- **Automated PoC Generation**: For critical findings

---

*Report generated by Web3 Hunter - Agentic Smart Contract Security Platform*
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md)
        
        return {
            "markdown_path": filepath,
            "filename": filename
        }
